# A sample TOML config file.
[connections]
Provider="postgres"
DBConnection="postgresql://root@localhost:26257/a_word_a_day?sslmode=disable"
DBName="a_word_a_day"
NATSURL="nats://localhost:4222"

# A sample TOML config file.
[connections_cloud]
Provider="postgres"
DBConnection="postgresql://root@node_1:26257/a_word_a_day?sslmode=disable"
DBName="a_word_a_day"
NATSURL="nats://aWordADay_nats:4222"

[casbin]
DBName="casbin"
ModelConf="basic_model.conf"
