version: "3"
services:
  node_1:
    container_name: node_1
    image: cockroachdb/cockroach:latest
    restart: "unless-stopped"
    environment: 
      COCKROACH_USER: root
      COCKROACH_DB: a_word_a_day
    volumes:
      - ./data/node_1:/cockroach/cockroach-data
      - ./scripts/cockroach-init.sh:/cockroach/cockroach-init.sh
    entrypoint: "/bin/bash /cockroach/cockroach-init.sh"
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - cockroachdb_net

  nats:
    container_name: aWordADay_nats
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - cockroachdb_net
  app:
    container_name: awordaday
    restart: always
    build: ./
    ports:
      - "50051:50051"
    links:
      - node_1
    depends_on:
      - node_1
    networks: 
      - cockroachdb_net 
      
networks:
    cockroachdb_net:
        driver: bridge